//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMappingway.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniMappingway.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Border Brightness.
        /// </summary>
        internal static string BorderBrightness {
            get {
                return ResourceManager.GetString("BorderBrightness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Border Radius.
        /// </summary>
        internal static string BorderRadius {
            get {
                return ResourceManager.GetString("BorderRadius", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Circle Size.
        /// </summary>
        internal static string CircleSize {
            get {
                return ResourceManager.GetString("CircleSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opens Mini-Mappingway settings.
        /// </summary>
        internal static string CommandHelpMessage {
            get {
                return ResourceManager.GetString("CommandHelpMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;Everyone&quot; is always the lowest priority.
        /// </summary>
        internal static string EveryoneLowestPriority {
            get {
                return ResourceManager.GetString("EveryoneLowestPriority", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you have a common FC tag you may wish to disable this..
        /// </summary>
        internal static string FcTagCommonNotice {
            get {
                return ResourceManager.GetString("FcTagCommonNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For now FC members are found by comparing FC tags..
        /// </summary>
        internal static string FcTagComparisonNotice {
            get {
                return ResourceManager.GetString("FcTagComparisonNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Marker Colour. Click the colored square for a picker..
        /// </summary>
        internal static string MarkerColourDescription {
            get {
                return ResourceManager.GetString("MarkerColourDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Marker settings, ordered by priority:.
        /// </summary>
        internal static string MarkerSettingsHeader {
            get {
                return ResourceManager.GetString("MarkerSettingsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Priority, higher shows on top of lower.
        /// </summary>
        internal static string PriorityDescription {
            get {
                return ResourceManager.GetString("PriorityDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Priority {0} is already taken.
        /// </summary>
        internal static string PriorityTaken {
            get {
                return ResourceManager.GetString("PriorityTaken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dot radius.
        /// </summary>
        internal static string PvpRadarDotRadius {
            get {
                return ResourceManager.GetString("PvpRadarDotRadius", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable PvP player radar (on-screen dots).
        /// </summary>
        internal static string PvpRadarEnabled {
            get {
                return ResourceManager.GetString("PvpRadarEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enemy colour.
        /// </summary>
        internal static string PvpRadarEnemyColor {
            get {
                return ResourceManager.GetString("PvpRadarEnemyColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friendly colour.
        /// </summary>
        internal static string PvpRadarFriendlyColor {
            get {
                return ResourceManager.GetString("PvpRadarFriendlyColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PvP Player Radar.
        /// </summary>
        internal static string PvpRadarHeader {
            get {
                return ResourceManager.GetString("PvpRadarHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide friendly players.
        /// </summary>
        internal static string PvpRadarHideFriendly {
            get {
                return ResourceManager.GetString("PvpRadarHideFriendly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Projects nearby players onto the screen. Intended for Frontline and other PvP areas..
        /// </summary>
        internal static string PvpRadarNotice {
            get {
                return ResourceManager.GetString("PvpRadarNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only show dots (no player names).
        /// </summary>
        internal static string PvpRadarOnlyDot {
            get {
                return ResourceManager.GetString("PvpRadarOnlyDot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Also show outside PvP areas.
        /// </summary>
        internal static string PvpRadarOutsidePvp {
            get {
                return ResourceManager.GetString("PvpRadarOutsidePvp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mini-Mappingway Settings.
        /// </summary>
        internal static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Border.
        /// </summary>
        internal static string ShowBorder {
            get {
                return ResourceManager.GetString("ShowBorder", resourceCulture);
            }
        }
    }
}
